export const FILTERS = {
  world: [
    { key: 'all',      label: 'All Regions' },
    { key: 'Africa',   label: 'Africa'   },
    { key: 'Asia',     label: 'Asia'     },
    { key: 'Europe',   label: 'Europe'   },
    { key: 'Americas', label: 'Americas' },
    { key: 'Oceania',  label: 'Oceania'  },
  ],
  states: [
    { key: 'all',       label: 'All States' },
    { key: 'Northeast', label: 'Northeast'  },
    { key: 'South',     label: 'South'      },
    { key: 'Midwest',   label: 'Midwest'    },
    { key: 'West',      label: 'West'       },
  ],
  ireland: [
    { key: 'all',      label: 'All Counties' },
    { key: 'Munster',  label: 'Munster'   },
    { key: 'Leinster', label: 'Leinster'  },
    { key: 'Connacht', label: 'Connacht'  },
    { key: 'Ulster',   label: 'Ulster'    },
  ],
  france: [
    { key: 'all',       label: 'All Regions' },
    { key: 'North',     label: 'North'       },
    { key: 'Northwest', label: 'Northwest'   },
    { key: 'Center',    label: 'Center'      },
    { key: 'East',      label: 'East'        },
    { key: 'South',     label: 'South'       },
    { key: 'Southwest', label: 'Southwest'   },
    { key: 'Overseas',  label: 'Overseas'    },
  ],
  germany: [
    { key: 'all',       label: 'All States' },
    { key: 'North',     label: 'North'      },
    { key: 'Northwest', label: 'Northwest'  },
    { key: 'West',      label: 'West'       },
    { key: 'Center',    label: 'Center'     },
    { key: 'East',      label: 'East'       },
    { key: 'South',     label: 'South'      },
  ],
  spain: [
    { key: 'all',       label: 'All Provinces' },
    { key: 'North',     label: 'North'         },
    { key: 'Northeast', label: 'Northeast'     },
    { key: 'East',      label: 'East'          },
    { key: 'Center',    label: 'Center'        },
    { key: 'South',     label: 'South'         },
    { key: 'Islands',   label: 'Islands'       },
  ],
  japan: [
    { key: 'all',      label: 'All Prefectures' },
    { key: 'Hokkaido', label: 'Hokkaidō'        },
    { key: 'Tohoku',   label: 'Tōhoku'          },
    { key: 'Kanto',    label: 'Kantō'           },
    { key: 'Chubu',    label: 'Chūbu'           },
    { key: 'Kansai',   label: 'Kansai'          },
    { key: 'Chugoku',  label: 'Chūgoku'         },
    { key: 'Shikoku',  label: 'Shikoku'         },
    { key: 'Kyushu',   label: 'Kyūshū'          },
  ],
  australia: [
    { key: 'all',       label: 'All States'  },
    { key: 'East',      label: 'East'        },
    { key: 'Northeast', label: 'Queensland'  },
    { key: 'South',     label: 'South'       },
    { key: 'West',      label: 'West'        },
    { key: 'North',     label: 'North'       },
  ],
  canada: [
    { key: 'all',          label: 'All Provinces'  },
    { key: 'Atlantic',     label: 'Atlantic'       },
    { key: 'Central',      label: 'Central'        },
    { key: 'Prairie',      label: 'Prairie'        },
    { key: 'Pacific',      label: 'Pacific'        },
    { key: 'Territories',  label: 'Territories'    },
  ],
  brazil: [
    { key: 'all',          label: 'All States'   },
    { key: 'Norte',        label: 'Norte'        },
    { key: 'Nordeste',     label: 'Nordeste'     },
    { key: 'Centro-Oeste', label: 'Centro-Oeste' },
    { key: 'Sudeste',      label: 'Sudeste'      },
    { key: 'Sul',          label: 'Sul'          },
  ],
  mexico: [
    { key: 'all',       label: 'All States'  },
    { key: 'North',     label: 'North'       },
    { key: 'Pacific',   label: 'Pacific'     },
    { key: 'Center',    label: 'Center'      },
    { key: 'Southeast', label: 'Southeast'   },
  ],
  india: [
    { key: 'all',       label: 'All States'  },
    { key: 'North',     label: 'North'       },
    { key: 'West',      label: 'West'        },
    { key: 'Central',   label: 'Central'     },
    { key: 'East',      label: 'East'        },
    { key: 'Northeast', label: 'Northeast'   },
    { key: 'South',     label: 'South'       },
    { key: 'Islands',   label: 'Islands'     },
  ],
  china: [
    { key: 'all',       label: 'All Provinces' },
    { key: 'Northeast', label: 'Northeast'     },
    { key: 'North',     label: 'North'         },
    { key: 'Northwest', label: 'Northwest'     },
    { key: 'East',      label: 'East'          },
    { key: 'Central',   label: 'Central'       },
    { key: 'South',     label: 'South'         },
    { key: 'Southwest', label: 'Southwest'     },
  ],
  southafrica: [
    { key: 'all',      label: 'All Provinces' },
    { key: 'Coastal',  label: 'Coastal'       },
    { key: 'Northern', label: 'Northern'      },
    { key: 'Interior', label: 'Interior'      },
  ],
  argentina: [
    { key: 'all',       label: 'All Provinces' },
    { key: 'Noroeste',  label: 'Noroeste'      },
    { key: 'Noreste',   label: 'Noreste'       },
    { key: 'Cuyo',      label: 'Cuyo'          },
    { key: 'Pampeana',  label: 'Pampeana'      },
    { key: 'Patagonia', label: 'Patagonia'     },
  ],
  nigeria: [
    { key: 'all',           label: 'All States'  },
    { key: 'Southwest',     label: 'Southwest'   },
    { key: 'Southeast',     label: 'Southeast'   },
    { key: 'South-South',   label: 'South-South' },
    { key: 'North Central', label: 'N. Central'  },
    { key: 'Northeast',     label: 'Northeast'   },
    { key: 'Northwest',     label: 'Northwest'   },
  ],
  indonesia: [
    { key: 'all',         label: 'All Provinces' },
    { key: 'Sumatra',     label: 'Sumatra'       },
    { key: 'Java',        label: 'Java'          },
    { key: 'Kalimantan',  label: 'Kalimantan'    },
    { key: 'Sulawesi',    label: 'Sulawesi'      },
    { key: 'Eastern',     label: 'Eastern'       },
  ],
  newzealand: [
    { key: 'all',          label: 'All Regions'  },
    { key: 'North Island', label: 'North Island' },
    { key: 'South Island', label: 'South Island' },
  ],
  egypt: [
    { key: 'all',         label: 'All Governorates' },
    { key: 'Lower Egypt', label: 'Lower Egypt'      },
    { key: 'Upper Egypt', label: 'Upper Egypt'      },
    { key: 'Canal',       label: 'Canal Zone'       },
    { key: 'Sinai',       label: 'Sinai'            },
    { key: 'Frontier',    label: 'Frontier'         },
  ],
  turkey: [
    { key: 'all',              label: 'All Provinces'  },
    { key: 'Marmara',          label: 'Marmara'        },
    { key: 'Aegean',           label: 'Aegean'         },
    { key: 'Mediterranean',    label: 'Mediterranean'  },
    { key: 'Central Anatolia', label: 'Central'        },
    { key: 'Black Sea',        label: 'Black Sea'      },
    { key: 'East',             label: 'East Anatolia'  },
    { key: 'Southeast',        label: 'Southeast'      },
  ],
  poland: [
    { key: 'all',    label: 'All Voivodeships' },
    { key: 'North',  label: 'North'            },
    { key: 'Center', label: 'Center'           },
    { key: 'East',   label: 'East'             },
    { key: 'South',  label: 'South'            },
  ],
  romania: [
    { key: 'all',       label: 'All Counties' },
    { key: 'Northwest', label: 'Northwest'    },
    { key: 'Center',    label: 'Center'       },
    { key: 'Northeast', label: 'Northeast'    },
    { key: 'West',      label: 'West'         },
    { key: 'Southwest', label: 'Southwest'    },
    { key: 'South',     label: 'South'        },
    { key: 'Southeast', label: 'Southeast'    },
  ],
};
